---
- hosts: localhost
  become: no
  tasks:
#    - name: Download Jenkins docker image
#      unarchive:
#        src: http://bin-repo/docker/docker-jenkins.tar
#        dest: "{{ upload_dir }}"
#      with_items:
#        - "{{ docker_gitlab_image.tar }}"
#        - "{{ docker_jenkins_image.tar }}"

#    - name: Load docker images
#      shell: "docker load < {{ upload_dir }}/{{ item }}"
#      with_items:
#        - "{{ docker_gitlab_image.tar }}"
#        - "{{ docker_jenkins_image.tar }}"

#    - name: Install docker-compose
#      get_url:
#        url: "http://bin-repo/docker/{{ docker_compose_bin }}"
#        dest: /usr/local/bin/
#        mode: 744

    - name: Create PDC dir
      file:
        path: "{{ pdc_dir }}"
        state: directory
        mode: 0755

    - name: Upload docker-compose files
      template:
        src: "templates/docker-compose.{{ item.key }}.j2"
        dest: "{{ pdc_dir }}/docker-compose.{{ item.key }}.yml"
      with_dict: "{{ docker_images }}"

    - name: Create global docker-compose file
      shell: >-
        docker-compose
        -f {{ pdc_dir }}/docker-compose.gitlab.yml
        -f {{ pdc_dir }}/docker-compose.jenkins.yml
        -f {{ pdc_dir }}/docker-compose.registry.yml
        config > {{ pdc_dir }}/docker-compose.yml

    - name: Build it
      shell: docker-compose -f {{ pdc_dir }}/docker-compose.yml build

    - name: Run it
      shell: docker-compose -f {{ pdc_dir }}/docker-compose.yml up -d