---
- hosts: localhost
  become: no
  tasks:
#    - name: Download Jenkins docker image
#      unarchive:
#        src: "http://bin-repo/docker/{{ item.value.tar }}"
#        dest: "{{ upload_dir }}"
#      with_dict: "{{ docker_images }}"

    - name: Load docker images
      docker_image:
        name: "{{ item.value.name }}"
        tag: "{{ item.value.tag }}"
        load_path: "{{ upload_dir }}/{{ item.value.tar }}"
        state: present
      with_dict: "{{ docker_images }}"

#    - name: Install docker-compose
#      get_url:
#        url: "http://bin-repo/docker/{{ docker_compose_bin }}"
#        dest: /usr/local/bin/
#        mode: 744

    - name: Create PDC dir
      file:
        path: "{{ pdc_dir }}"
        state: directory
        mode: 0755

    - name: Upload docker-compose files
      template:
        src: "templates/docker-compose.{{ item.key }}.j2"
        dest: "{{ pdc_dir }}/docker-compose.{{ item.key }}.yml"
      with_dict: "{{ docker_images }}"

    - name: Create global docker-compose file
      shell: >-
        docker-compose
        -f {{ pdc_dir }}/docker-compose.gitlab.yml
        -f {{ pdc_dir }}/docker-compose.jenkins.yml
        -f {{ pdc_dir }}/docker-compose.registry.yml
        config > {{ pdc_dir }}/docker-compose.yml

    - name: Build it
      shell: docker-compose -f {{ pdc_dir }}/docker-compose.yml build

#    - name: Build and run
#      docker_service:
#        project_src: "{{ pdc_dir }}"
#        build: yes
#        state: present

    - name: Load image from archive and push it to registry
      docker_image:
        repository: "localhost:5000/{{ item.value.name }}"
        push: yes
        name: "{{ item.value.name }}"
        tag: "{{ item.value.tag }}"
        load_path: "{{ upload_dir }}/{{ item.value.tar }}"
        state: present
      with_dict: "{{ docker_images }}"