---
- hosts: localhost
  become: no
  tasks:
#    - name: Download Jenkins docker image
#      unarchive:
#        src: http://bin-repo/docker/docker-jenkins.tar
#        dest: "{{ upload_dir }}"
#      with_items:
#        - "{{ docker_gitlab_image.tar }}"
#        - "{{ docker_jenkins_image.tar }}"

    - name: Load docker images
      shell: "docker load < {{ upload_dir }}/{{ item }}"
      with_items:
        - "{{ docker_gitlab_image.tar }}"
        - "{{ docker_jenkins_image.tar }}"

    - name: Create PDC dir
      file:
        path: "{{ pdc_dir }}"
        state: directory
        mode: 0755

    - name: Upload docker-compose files
      template:
        src: "templates/docker-compose.{{ item }}.j2"
        dest: "{{ pdc_dir }}/docker-compose.{{ item }}.yml"
      with_items:
        - gitlab
        - jenkins

    - name: Create global docker-compose file
      shell: >-
        docker-compose
        -f {{ pdc_dir }}/docker-compose.gitlab.yml
        -f {{ pdc_dir }}/docker-compose.jenkins.yml
        config > {{ pdc_dir }}/docker-compose.yml

    - name: Build it
      shell: docker-compose -f {{ pdc_dir }}/docker-compose.yml build

    - name: Run it
      shell: docker-compose -f {{ pdc_dir }}/docker-compose.yml up -d