networks:
  pdc_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.238.0/24
      driver: default
services:
  giltab:
    environment:
      GITLAB_OMNIBUS_CONFIG: external_url 'http://192.168.1.27'
    hostname: gitlab.infra.corp
    image: gitlab-ce:latest
    networks:
      pdc_net: null
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 1342/tcp
    restart: always
    volumes:
    - gitlab-config:/etc/gitlab:rw
    - gitlab-logs:/var/log/gitlab:rw
    - gitlab-data:/var/opt/gitlab:rw
  jenkins-master:
    image: jenkins:latest
    networks:
      pdc_net: null
    ports:
    - 8080:8080/tcp
    restart: always
    volumes:
    - jenkins-data:/var/jenkins_home:rw
    - /home/joel/ownCloud/Development/pdc/log:/var/log/jenkins:rw
version: '3.0'
volumes:
  gitlab-config: {}
  gitlab-data: {}
  gitlab-logs: {}
  jenkins-data: {}

